import { Knex } from "knex";

export async function seed(knex: Knex): Promise<void> {
  // Deletes ALL existing entries
  await knex("products").del();

  // Inserts seed entries
  await knex("products").insert([
    // Commodity White Eggs
    {
      product_id: 101,
      name: "Commodity White Eggs - 12 Count",
      description:
        "Fresh commodity white eggs, 12 count carton. Perfect for everyday cooking and baking.",
      category: "commodity",
      product_color: "white",
      product_count: 12,
      images: JSON.stringify([
        "/assets/eggs/Commodity White Eggs/101-commodity.png",
        "https://unsplash.com/photos/five-broil-eggs-g8xdO1Q1kIg",
      ]),
      b2c_price: 3.99,
      b2b_price: 2.99,
      inventory_by_carton: 150,
      inventory_by_box: 25,
      is_available: true,
      is_active: true,
    },
    {
      product_id: 102,
      name: "Commodity White Eggs - 18 Count",
      description:
        "Fresh commodity white eggs, 18 count carton. Great value for larger families.",
      category: "commodity",
      product_color: "white",
      product_count: 18,
      images: JSON.stringify([
        "/assets/eggs/Commodity White Eggs/102-commodity.png",
      ]),
      b2c_price: 5.49,
      b2b_price: 4.19,
      inventory_by_carton: 120,
      inventory_by_box: 20,
      is_available: true,
      is_active: true,
    },
    {
      product_id: 103,
      name: "Commodity White Eggs - 24 Count",
      description:
        "Fresh commodity white eggs, 24 count carton. Ideal for restaurants and food service.",
      category: "commodity",
      product_color: "white",
      product_count: 24,
      images: JSON.stringify([
        "/assets/eggs/Commodity White Eggs/103-commodity.png",
      ]),
      b2c_price: 6.99,
      b2b_price: 5.29,
      inventory_by_carton: 100,
      inventory_by_box: 15,
      is_available: true,
      is_active: true,
    },
    {
      product_id: 104,
      name: "Commodity White Eggs - 30 Count",
      description:
        "Fresh commodity white eggs, 30 count carton. Perfect for high-volume cooking.",
      category: "commodity",
      product_color: "white",
      product_count: 30,
      images: JSON.stringify([
        "/assets/eggs/Commodity White Eggs/104-commodity.png",
      ]),
      b2c_price: 8.49,
      b2b_price: 6.49,
      inventory_by_carton: 80,
      inventory_by_box: 12,
      is_available: true,
      is_active: true,
    },
    {
      product_id: 105,
      name: "Commodity White Eggs - 36 Count",
      description:
        "Fresh commodity white eggs, 36 count carton. Great for commercial kitchens.",
      category: "commodity",
      product_color: "white",
      product_count: 36,
      images: JSON.stringify([
        "/assets/eggs/Commodity White Eggs/105-commodity.png",
      ]),
      b2c_price: 9.99,
      b2b_price: 7.69,
      inventory_by_carton: 60,
      inventory_by_box: 10,
      is_available: true,
      is_active: true,
    },
    {
      product_id: 106,
      name: "Commodity White Eggs - 48 Count",
      description:
        "Fresh commodity white eggs, 48 count carton. Maximum value for bulk purchases.",
      category: "commodity",
      product_color: "white",
      product_count: 48,
      images: JSON.stringify([
        "/assets/eggs/Commodity White Eggs/106-commodity.png",
      ]),
      b2c_price: 12.99,
      b2b_price: 9.99,
      inventory_by_carton: 40,
      inventory_by_box: 8,
      is_available: true,
      is_active: true,
    },
    {
      product_id: 109,
      name: "Commodity White Eggs - 60 Count",
      description:
        "Fresh commodity white eggs, 60 count carton. Ultimate bulk option for commercial use.",
      category: "commodity",
      product_color: "white",
      product_count: 60,
      images: JSON.stringify([
        "/assets/eggs/Commodity White Eggs/109-commodity.png",
      ]),
      b2c_price: 15.99,
      b2b_price: 12.49,
      inventory_by_carton: 30,
      inventory_by_box: 6,
      is_available: true,
      is_active: true,
    },
    {
      product_id: 110,
      name: "Commodity White Eggs - 72 Count",
      description:
        "Fresh commodity white eggs, 72 count carton. Premium bulk option for large operations.",
      category: "commodity",
      product_color: "white",
      product_count: 72,
      images: JSON.stringify([
        "/assets/eggs/Commodity White Eggs/110-commodity.png",
      ]),
      b2c_price: 18.99,
      b2b_price: 14.99,
      inventory_by_carton: 25,
      inventory_by_box: 5,
      is_available: true,
      is_active: true,
    },
    // Commodity Brown Eggs
    {
      product_id: 111,
      name: "Commodity Brown Eggs - 12 Count",
      description:
        "Fresh commodity brown eggs, 12 count carton. Rich flavor and golden yolks.",
      category: "commodity",
      product_color: "brown",
      product_count: 12,
      images: JSON.stringify([
        "/assets/eggs/Commodity Brown Eggs/111-commodity.png",
      ]),
      b2c_price: 4.49,
      b2b_price: 3.39,
      inventory_by_carton: 120,
      inventory_by_box: 20,
      is_available: true,
      is_active: true,
    },
    {
      product_id: 112,
      name: "Commodity Brown Eggs - 18 Count",
      description:
        "Fresh commodity brown eggs, 18 count carton. Perfect for families who prefer brown eggs.",
      category: "commodity",
      product_color: "brown",
      product_count: 18,
      images: JSON.stringify([
        "/assets/eggs/Commodity Brown Eggs/112-commodity.png",
      ]),
      b2c_price: 6.19,
      b2b_price: 4.79,
      inventory_by_carton: 100,
      inventory_by_box: 15,
      is_available: true,
      is_active: true,
    },
    {
      product_id: 113,
      name: "Commodity Brown Eggs - 24 Count",
      description:
        "Fresh commodity brown eggs, 24 count carton. Great for restaurants and bakeries.",
      category: "commodity",
      product_color: "brown",
      product_count: 24,
      images: JSON.stringify([
        "/assets/eggs/Commodity Brown Eggs/113-commodity.png",
      ]),
      b2c_price: 7.89,
      b2b_price: 6.09,
      inventory_by_carton: 80,
      inventory_by_box: 12,
      is_available: true,
      is_active: true,
    },
    {
      product_id: 114,
      name: "Commodity Brown Eggs - 30 Count",
      description:
        "Fresh commodity brown eggs, 30 count carton. Ideal for high-volume commercial use.",
      category: "commodity",
      product_color: "brown",
      product_count: 30,
      images: JSON.stringify([
        "/assets/eggs/Commodity Brown Eggs/114-commodity.png",
      ]),
      b2c_price: 9.59,
      b2b_price: 7.39,
      inventory_by_carton: 60,
      inventory_by_box: 10,
      is_available: true,
      is_active: true,
    },
    {
      product_id: 115,
      name: "Commodity Brown Eggs - 36 Count",
      description:
        "Fresh commodity brown eggs, 36 count carton. Perfect for large commercial kitchens.",
      category: "commodity",
      product_color: "brown",
      product_count: 36,
      images: JSON.stringify([
        "/assets/eggs/Commodity Brown Eggs/115-commodity.png",
      ]),
      b2c_price: 11.29,
      b2b_price: 8.79,
      inventory_by_carton: 50,
      inventory_by_box: 8,
      is_available: true,
      is_active: true,
    },
    // Organic Brown Eggs
    {
      product_id: 121,
      name: "Organic Brown Eggs - 12 Count",
      description:
        "Certified organic brown eggs, 12 count carton. Free-range, no antibiotics or hormones.",
      category: "organic",
      product_color: "brown",
      product_count: 12,
      images: JSON.stringify([
        "/assets/eggs/Organic Brown Eggs/121-organic.png",
      ]),
      b2c_price: 6.99,
      b2b_price: 5.29,
      inventory_by_carton: 80,
      inventory_by_box: 15,
      is_available: true,
      is_active: true,
    },
    {
      product_id: 122,
      name: "Organic Brown Eggs - 18 Count",
      description:
        "Certified organic brown eggs, 18 count carton. Premium quality for health-conscious consumers.",
      category: "organic",
      product_color: "brown",
      product_count: 18,
      images: JSON.stringify([
        "/assets/eggs/Organic Brown Eggs/122-organic.png",
      ]),
      b2c_price: 9.99,
      b2b_price: 7.69,
      inventory_by_carton: 60,
      inventory_by_box: 12,
      is_available: true,
      is_active: true,
    },
    {
      product_id: 123,
      name: "Organic Brown Eggs - 24 Count",
      description:
        "Certified organic brown eggs, 24 count carton. Perfect for organic restaurants and cafes.",
      category: "organic",
      product_color: "brown",
      product_count: 24,
      images: JSON.stringify([
        "/assets/eggs/Organic Brown Eggs/123-organic.png",
      ]),
      b2c_price: 12.99,
      b2b_price: 9.99,
      inventory_by_carton: 50,
      inventory_by_box: 10,
      is_available: true,
      is_active: true,
    },
    {
      product_id: 125,
      name: "Organic Brown Eggs - 30 Count",
      description:
        "Certified organic brown eggs, 30 count carton. Ideal for organic food service operations.",
      category: "organic",
      product_color: "brown",
      product_count: 30,
      images: JSON.stringify([
        "/assets/eggs/Organic Brown Eggs/125-organic.png",
      ]),
      b2c_price: 15.99,
      b2b_price: 12.49,
      inventory_by_carton: 40,
      inventory_by_box: 8,
      is_available: true,
      is_active: true,
    },
    {
      product_id: 126,
      name: "Organic Brown Eggs - 36 Count",
      description:
        "Certified organic brown eggs, 36 count carton. Premium bulk option for organic establishments.",
      category: "organic",
      product_color: "brown",
      product_count: 36,
      images: JSON.stringify([
        "/assets/eggs/Organic Brown Eggs/126-organic.png",
      ]),
      b2c_price: 18.99,
      b2b_price: 14.99,
      inventory_by_carton: 30,
      inventory_by_box: 6,
      is_available: true,
      is_active: true,
    },
    {
      product_id: 127,
      name: "Organic Brown Eggs - 48 Count",
      description:
        "Certified organic brown eggs, 48 count carton. Maximum value for organic bulk purchases.",
      category: "organic",
      product_color: "brown",
      product_count: 48,
      images: JSON.stringify([
        "/assets/eggs/Organic Brown Eggs/127-organic.png",
      ]),
      b2c_price: 23.99,
      b2b_price: 18.99,
      inventory_by_carton: 25,
      inventory_by_box: 5,
      is_available: true,
      is_active: true,
    },
    // Cage Free Brown Eggs
    {
      product_id: 131,
      name: "Cage Free Brown Eggs - 12 Count",
      description:
        "Cage-free brown eggs, 12 count carton. Hens raised in spacious, humane conditions.",
      category: "cage-free",
      product_color: "brown",
      product_count: 12,
      images: JSON.stringify([
        "/assets/eggs/Cage Free Brown Eggs/131-cage-free.png",
      ]),
      b2c_price: 5.49,
      b2b_price: 4.19,
      inventory_by_carton: 100,
      inventory_by_box: 18,
      is_available: true,
      is_active: true,
    },
    {
      product_id: 132,
      name: "Cage Free Brown Eggs - 18 Count",
      description:
        "Cage-free brown eggs, 18 count carton. Ethical choice for families and businesses.",
      category: "cage-free",
      product_color: "brown",
      product_count: 18,
      images: JSON.stringify([
        "/assets/eggs/Cage Free Brown Eggs/132-cage-free.png",
      ]),
      b2c_price: 7.99,
      b2b_price: 6.19,
      inventory_by_carton: 80,
      inventory_by_box: 15,
      is_available: true,
      is_active: true,
    },
    {
      product_id: 133,
      name: "Cage Free Brown Eggs - 24 Count",
      description:
        "Cage-free brown eggs, 24 count carton. Perfect for restaurants with ethical sourcing policies.",
      category: "cage-free",
      product_color: "brown",
      product_count: 24,
      images: JSON.stringify([
        "/assets/eggs/Cage Free Brown Eggs/133-cage-free.png",
      ]),
      b2c_price: 10.49,
      b2b_price: 8.19,
      inventory_by_carton: 60,
      inventory_by_box: 12,
      is_available: true,
      is_active: true,
    },
    {
      product_id: 134,
      name: "Cage Free Brown Eggs - 30 Count",
      description:
        "Cage-free brown eggs, 30 count carton. Ideal for food service with humane animal practices.",
      category: "cage-free",
      product_color: "brown",
      product_count: 30,
      images: JSON.stringify([
        "/assets/eggs/Cage Free Brown Eggs/134-cage-free.png",
      ]),
      b2c_price: 12.99,
      b2b_price: 10.19,
      inventory_by_carton: 50,
      inventory_by_box: 10,
      is_available: true,
      is_active: true,
    },
    {
      product_id: 135,
      name: "Cage Free Brown Eggs - 36 Count",
      description:
        "Cage-free brown eggs, 36 count carton. Premium bulk option for ethical establishments.",
      category: "cage-free",
      product_color: "brown",
      product_count: 36,
      images: JSON.stringify([
        "/assets/eggs/Cage Free Brown Eggs/135-cage-free.png",
      ]),
      b2c_price: 15.49,
      b2b_price: 12.19,
      inventory_by_carton: 40,
      inventory_by_box: 8,
      is_available: true,
      is_active: true,
    },
    // Cage Free White Eggs
    {
      product_id: 136,
      name: "Cage Free White Eggs - 12 Count",
      description:
        "Cage-free white eggs, 12 count carton. Hens raised in spacious, humane conditions.",
      category: "cage-free",
      product_color: "white",
      product_count: 12,
      images: JSON.stringify([
        "/assets/eggs/Cage Free White Eggs/136-cage-free.png",
      ]),
      b2c_price: 5.19,
      b2b_price: 3.99,
      inventory_by_carton: 100,
      inventory_by_box: 18,
      is_available: true,
      is_active: true,
    },
    {
      product_id: 137,
      name: "Cage Free White Eggs - 18 Count",
      description:
        "Cage-free white eggs, 18 count carton. Ethical choice for families and businesses.",
      category: "cage-free",
      product_color: "white",
      product_count: 18,
      images: JSON.stringify([
        "/assets/eggs/Cage Free White Eggs/137-cage-free.png",
      ]),
      b2c_price: 7.69,
      b2b_price: 5.99,
      inventory_by_carton: 80,
      inventory_by_box: 15,
      is_available: true,
      is_active: true,
    },
    // Specialty Eggs
    {
      product_id: 142,
      name: "Quail Eggs - 12 Count",
      description:
        "Delicate quail eggs, 12 count carton. Perfect for gourmet dishes and specialty cuisine.",
      category: "specialty",
      product_color: "white",
      product_count: 12,
      images: JSON.stringify(["/assets/eggs/Quail White Eggs/142-copy.png"]),
      b2c_price: 8.99,
      b2b_price: 6.99,
      inventory_by_carton: 30,
      inventory_by_box: 8,
      is_available: true,
      is_active: true,
    },
    {
      product_id: 143,
      name: "Duck Eggs - 12 Count",
      description:
        "Rich duck eggs, 12 count carton. Larger yolks and richer flavor than chicken eggs.",
      category: "specialty",
      product_color: "white",
      product_count: 12,
      images: JSON.stringify(["/assets/eggs/Duck White Eggs/143-duck.png"]),
      b2c_price: 9.99,
      b2b_price: 7.79,
      inventory_by_carton: 25,
      inventory_by_box: 6,
      is_available: true,
      is_active: true,
    },
    {
      product_id: 145,
      name: "Hard Boiled Eggs - 12 Count",
      description:
        "Pre-cooked hard boiled eggs, 12 count carton. Ready to eat, perfect for snacks and salads.",
      category: "specialty",
      product_color: "white",
      product_count: 12,
      images: JSON.stringify([
        "/assets/eggs/Hard Boiled Eggs/145-hard-boiled.png",
      ]),
      b2c_price: 7.99,
      b2b_price: 6.19,
      inventory_by_carton: 40,
      inventory_by_box: 10,
      is_available: true,
      is_active: true,
    },
    // Pasture Raised Eggs
    {
      product_id: 146,
      name: "Pasture Raised Brown Eggs - 12 Count",
      description:
        "Pasture-raised brown eggs, 12 count carton. Hens forage on natural pasture for optimal nutrition.",
      category: "pasture-raised",
      product_color: "brown",
      product_count: 12,
      images: JSON.stringify([
        "/assets/eggs/Pasture Raised Brown Eggs/146-pasture.png",
      ]),
      b2c_price: 8.99,
      b2b_price: 6.99,
      inventory_by_carton: 50,
      inventory_by_box: 12,
      is_available: true,
      is_active: true,
    },
    {
      product_id: 147,
      name: "Pasture Raised Brown Eggs - 18 Count",
      description:
        "Pasture-raised brown eggs, 18 count carton. Premium quality with superior nutritional profile.",
      category: "pasture-raised",
      product_color: "brown",
      product_count: 18,
      images: JSON.stringify([
        "/assets/eggs/Pasture Raised Brown Eggs/147-pasture.png",
      ]),
      b2c_price: 12.99,
      b2b_price: 10.19,
      inventory_by_carton: 40,
      inventory_by_box: 10,
      is_available: true,
      is_active: true,
    },
    // Heirloom Eggs
    {
      product_id: 148,
      name: "Heirloom Blue Eggs - 12 Count",
      description:
        "Heirloom blue eggs, 12 count carton. Rare heritage breed with beautiful blue shells.",
      category: "heirloom",
      product_color: "blue",
      product_count: 12,
      images: JSON.stringify([
        "/assets/eggs/Heirloom Blue & Brown Eggs/148-heirloom-blue.png",
      ]),
      b2c_price: 11.99,
      b2b_price: 9.29,
      inventory_by_carton: 20,
      inventory_by_box: 5,
      is_available: true,
      is_active: true,
    },
    {
      product_id: 149,
      name: "Heirloom Brown Eggs - 12 Count",
      description:
        "Heirloom brown eggs, 12 count carton. Heritage breed with rich flavor and golden yolks.",
      category: "heirloom",
      product_color: "brown",
      product_count: 12,
      images: JSON.stringify([
        "/assets/eggs/Heirloom Blue & Brown Eggs/149-heirloom-brown.png",
      ]),
      b2c_price: 10.99,
      b2b_price: 8.49,
      inventory_by_carton: 25,
      inventory_by_box: 6,
      is_available: true,
      is_active: true,
    },
  ]);

  console.log(`✅ Successfully seeded 35 products`);
}
