import { Knex } from 'knex';

// Pricing strategy:
// - Commodity: Base price
// - Cage-free: +15% premium
// - Organic: +25% premium  
// - Pasture-raised: +35% premium
// - Heirloom: +50% premium
// - Specialty (quail, duck): +100% premium

const products = [
  // Commodity White Eggs
  {
    name: "Grade A Jumbo White Eggs",
    description: "Jumbo white eggs from our happy hens.",
    imageUrl: "/assets/eggs/commodity-white/101-commodity.png",
    category: "commodity",
    eggColor: "white",
    eggCount: 12,
    price: 3.99,
    wholesalePrice: 2.50,
    inventoryByCarton: 1500,
    inventoryByBox: 150,
  },
  {
    name: "Grade A Extra Large White Eggs",
    description: "Extra large white eggs from our happy hens.",
    imageUrl: "/assets/eggs/commodity-white/102-commodity.png",
    category: "commodity",
    eggColor: "white",
    eggCount: 12,
    price: 3.79,
    wholesalePrice: 2.40,
    inventoryByCarton: 1800,
    inventoryByBox: 180,
  },
  {
    name: "Grade A Large White Eggs",
    description: "Large white eggs from our happy hens.",
    imageUrl: "/assets/eggs/commodity-white/103-commodity.png",
    category: "commodity",
    eggColor: "white",
    eggCount: 12,
    price: 3.59,
    wholesalePrice: 2.30,
    inventoryByCarton: 2000,
    inventoryByBox: 200,
  },
  {
    name: "Grade A Medium White Eggs",
    description: "Medium white eggs from our happy hens.",
    imageUrl: "/assets/eggs/commodity-white/104-commodity.png",
    category: "commodity",
    eggColor: "white",
    eggCount: 12,
    price: 3.39,
    wholesalePrice: 2.20,
    inventoryByCarton: 1200,
    inventoryByBox: 120,
  },
  {
    name: "Grade A Large White Eggs (18ct)",
    description: "Large white eggs from our happy hens - 18 count carton.",
    imageUrl: "/assets/eggs/commodity-white/105-commodity.png",
    category: "commodity",
    eggColor: "white",
    eggCount: 18,
    price: 5.39,
    wholesalePrice: 3.45,
    inventoryByCarton: 1000,
    inventoryByBox: 100,
  },
  {
    name: "Grade A Large White Eggs (6ct)",
    description: "Large white eggs from our happy hens - 6 count carton.",
    imageUrl: "/assets/eggs/commodity-white/106-commodity.png",
    category: "commodity",
    eggColor: "white",
    eggCount: 6,
    price: 1.99,
    wholesalePrice: 1.25,
    inventoryByCarton: 800,
    inventoryByBox: 80,
  },
  {
    name: "Grade A Large White Eggs (30ct)",
    description: "Large white eggs from our happy hens - 30 count carton.",
    imageUrl: "/assets/eggs/commodity-white/109-commodity.png",
    category: "commodity",
    eggColor: "white",
    eggCount: 30,
    price: 8.99,
    wholesalePrice: 5.75,
    inventoryByCarton: 600,
    inventoryByBox: 60,
  },

  // Commodity Brown Eggs
  {
    name: "Grade A Jumbo Brown Eggs",
    description: "Jumbo brown eggs from our happy hens.",
    imageUrl: "/assets/eggs/commodity-brown/111-commodity.png",
    category: "commodity",
    eggColor: "brown",
    eggCount: 12,
    price: 4.19,
    wholesalePrice: 2.65,
    inventoryByCarton: 1400,
    inventoryByBox: 140,
  },
  {
    name: "Grade A Extra Large Brown Eggs",
    description: "Extra large brown eggs from our happy hens.",
    imageUrl: "/assets/eggs/commodity-brown/112-commodity.png",
    category: "commodity",
    eggColor: "brown",
    eggCount: 12,
    price: 3.99,
    wholesalePrice: 2.55,
    inventoryByCarton: 1600,
    inventoryByBox: 160,
  },
  {
    name: "Grade A Large Brown Eggs",
    description: "Large brown eggs from our happy hens.",
    imageUrl: "/assets/eggs/commodity-brown/113-commodity.png",
    category: "commodity",
    eggColor: "brown",
    eggCount: 12,
    price: 3.79,
    wholesalePrice: 2.45,
    inventoryByCarton: 1800,
    inventoryByBox: 180,
  },

  // Organic Brown Eggs (25% premium)
  {
    name: "Organic Jumbo Brown Eggs",
    description: "Organic jumbo brown eggs from our happy hens.",
    imageUrl: "/assets/eggs/organic-brown/121-organic.png",
    category: "organic",
    eggColor: "brown",
    eggCount: 12,
    price: 4.99,
    wholesalePrice: 3.15,
    inventoryByCarton: 800,
    inventoryByBox: 80,
  },
  {
    name: "Organic Large Brown Eggs",
    description: "Organic large brown eggs from our happy hens.",
    imageUrl: "/assets/eggs/organic-brown/122-organic.png",
    category: "organic",
    eggColor: "brown",
    eggCount: 12,
    price: 4.79,
    wholesalePrice: 3.05,
    inventoryByCarton: 1000,
    inventoryByBox: 100,
  },
  {
    name: "Organic Medium Brown Eggs",
    description: "Organic medium brown eggs from our happy hens.",
    imageUrl: "/assets/eggs/organic-brown/123-organic.png",
    category: "organic",
    eggColor: "brown",
    eggCount: 12,
    price: 4.59,
    wholesalePrice: 2.95,
    inventoryByCarton: 600,
    inventoryByBox: 60,
  },

  // Cage-Free Brown Eggs (15% premium)
  {
    name: "Grade A Cage-Free Jumbo Brown Eggs",
    description: "Cage-free jumbo brown eggs from our happy hens.",
    imageUrl: "/assets/eggs/cage-free-brown/131-cage-free.png",
    category: "cage-free",
    eggColor: "brown",
    eggCount: 12,
    price: 4.59,
    wholesalePrice: 2.90,
    inventoryByCarton: 1200,
    inventoryByBox: 120,
  },
  {
    name: "Grade A Cage-Free Large Brown Eggs",
    description: "Cage-free large brown eggs from our happy hens.",
    imageUrl: "/assets/eggs/cage-free-brown/132-cage-free.png",
    category: "cage-free",
    eggColor: "brown",
    eggCount: 12,
    price: 4.39,
    wholesalePrice: 2.80,
    inventoryByCarton: 1400,
    inventoryByBox: 140,
  },

  // Cage-Free White Eggs
  {
    name: "Grade A Cage-Free Extra Large White Eggs",
    description: "Cage-free extra large white eggs from our happy hens.",
    imageUrl: "/assets/eggs/cage-free-white/136-cage-free.png",
    category: "cage-free",
    eggColor: "white",
    eggCount: 12,
    price: 4.39,
    wholesalePrice: 2.80,
    inventoryByCarton: 1200,
    inventoryByBox: 120,
  },

  // Specialty Eggs
  {
    name: "Fresh Quail Eggs",
    description: "Fresh quail eggs from our happy quails.",
    imageUrl: "/assets/eggs/quail/142-quail.png",
    category: "specialty",
    eggColor: "white",
    eggCount: 18,
    price: 7.99,
    wholesalePrice: 5.00,
    inventoryByCarton: 300,
    inventoryByBox: 30,
  },
  {
    name: "Fresh Duck Eggs",
    description: "Fresh duck eggs from our happy ducks.",
    imageUrl: "/assets/eggs/duck/143-duck.png",
    category: "specialty",
    eggColor: "white",
    eggCount: 6,
    price: 3.99,
    wholesalePrice: 2.50,
    inventoryByCarton: 200,
    inventoryByBox: 20,
  },
  {
    name: "Hard-Boiled Peeled Eggs",
    description: "Two hard-boiled and peeled eggs from our happy hens.",
    imageUrl: "/assets/eggs/hard-boiled/145-hard-boiled.png",
    category: "specialty",
    eggColor: "white",
    eggCount: 2,
    price: 2.99,
    wholesalePrice: 1.90,
    inventoryByCarton: 500,
    inventoryByBox: 50,
  },

  // Pasture-Raised Eggs (35% premium)
  {
    name: "Pasture-Raised Brown Eggs",
    description: "Pasture-Raised brown eggs from our happy hens.",
    imageUrl: "/assets/eggs/pasture-raised/146-pasture.png",
    category: "pasture-raised",
    eggColor: "brown",
    eggCount: 12,
    price: 4.99,
    wholesalePrice: 3.15,
    inventoryByCarton: 600,
    inventoryByBox: 60,
  },
  {
    name: "Pasture-Raised Organic Eggs",
    description: "Pasture-Raised organic brown eggs from our happy hens.",
    imageUrl: "/assets/eggs/pasture-raised/147-pasture.png",
    category: "pasture-raised",
    eggColor: "brown",
    eggCount: 12,
    price: 5.39,
    wholesalePrice: 3.40,
    inventoryByCarton: 400,
    inventoryByBox: 40,
  },

  // Heirloom Eggs (50% premium)
  {
    name: "Heirloom Blue Pasture Raised Eggs",
    description: "Heirloom blue pasture raised eggs from our happy hens.",
    imageUrl: "/assets/eggs/heirloom/148-heirloom-blue.png",
    category: "heirloom",
    eggColor: "blue",
    eggCount: 6,
    price: 4.99,
    wholesalePrice: 3.15,
    inventoryByCarton: 200,
    inventoryByBox: 20,
  },
  {
    name: "Heirloom Brown Pasture Raised Eggs",
    description: "Heirloom brown pasture raised eggs from our happy hens.",
    imageUrl: "/assets/eggs/heirloom/149-heirloom-brown.png",
    category: "heirloom",
    eggColor: "brown",
    eggCount: 6,
    price: 4.99,
    wholesalePrice: 3.15,
    inventoryByCarton: 200,
    inventoryByBox: 20,
  },
];

export async function seed(knex: Knex): Promise<void> {
  // Deletes ALL existing entries
  await knex('products').del();

  // Inserts seed entries
  await knex('products').insert(products);
} 